name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java:
        - 8
        - 9
        - 10
        - 11
        - 12
        - 13

    name: Build on Java ${{ matrix.java }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      # TODO: --scan
      run: ./gradlew build --stacktrace

  release:
    name: Release
    if: github.ref == 'master'
    runs-on: ubuntu-latest
    needs: build

    steps:

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: resourcebundlefix
        # Directory containing files to upload
        path: build/libs

    - name: Publish to GitHub Packages
      run: gradle publish
      env:
        REPOSITORY: ${{ github.repository }}
        USERNAME: ${{ github.actor }}
        PASSWORD: ${{ secrets.GITHUB_TOKEN }}

